essence/urls.py
from django.urls import path

from . import views

app_name = "essence"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("register/", views.register, name="register"),
    path("newyt/", views.YoutubeQuoteCreateView.as_view(), name="youtube_create"),
    path("newtext/", views.TextQuoteCreateView.as_view(), name="text_create"),
    path("textquote/", views.TextQuoteIndexView.as_view(), name="text_index"),
    path("youtubequote/", views.YoutubeQuoteIndexView.as_view(), name="youtube_index"),
    path("textquote/<int:pk>/", views.TextQuoteView.as_view(), name="text_detail"),
    path("youtubequote/<int:pk>/", views.YoutubeQuoteView.as_view(), name="youtube_detail"),
]

essence_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('essence/', include('essence.urls')),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("django.contrib.auth.urls")), 
]

essence/models.py
from django.db import models
from django.db.models import CheckConstraint, Q, F
from django.utils import timezone
from django.core import validators
from django.contrib.auth.models import User

# Create your models here.
class Quote(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    entry_timestamp = models.DateTimeField(default=timezone.now)
    

class YoutubeVideo(models.Model):
    id = models.CharField(max_length=11, primary_key=True)
    channel = models.CharField(max_length=200)
    title = models.TextField()
    length = models.IntegerField()

class TextQuote(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    metadata = models.OneToOneField(Quote, on_delete=models.CASCADE, primary_key=True)
    quote_text = models.TextField()
    author = models.CharField(max_length=200)
    text_title = models.CharField(max_length=200)

    def __str__(self):
        return '\"' + self.quote_text + '\", ' + self.text_title
    

class YoutubeQuote(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    metadata = models.OneToOneField(Quote, on_delete=models.CASCADE)
    youtube_id = models.ForeignKey(YoutubeVideo, on_delete=models.DO_NOTHING)
    start_seconds = models.IntegerField(validators=[validators.MinValueValidator(0)])
    end_seconds = models.IntegerField()

    class Meta:
        constraints = [
            CheckConstraint(
                check = Q(end_seconds__gt=F('start_seconds')), 
                name = 'check_end_seconds',
            ),
        ]

essence/forms.py
from typing import Any
from django import forms
from essence.models import YoutubeQuote, TextQuote
from essence.youtubeapi import video_id, video_info
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class QuoteForm(forms.ModelForm):
    title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder' :'Description', 'class': 'form-control', 'style': 'height: 8ch'}))

class YoutubeQuoteForm(QuoteForm):
    youtube_link = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Youtube Link', 'class': 'form-control'}))
    class Meta:
        model = YoutubeQuote
        fields = ["start_seconds", "end_seconds"]
        widgets = {
            'start_seconds': forms.NumberInput(attrs={
                'class': "form-control",
                'style': 'max-width: 16ch;',
                'placeholder': 'Start seconds'
                }),
            'end_seconds': forms.NumberInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 16ch;',
                'placeholder': 'End seconds'
                })
        }

    field_order = ["title", "description", "youtube_link", "start_seconds", "end_seconds"]

    def clean(self):
        youtube_id = self.cleaned_data["youtube_link"]
        start_seconds = self.cleaned_data["start_seconds"]
        end_seconds = self.cleaned_data["end_seconds"]

        length = video_info(video_id(youtube_id))["length"]
        if start_seconds >= end_seconds:
            self.add_error("start_seconds", "Start seconds must be less than End seconds")
            self.add_error("end_seconds", "End seconds must be greater than Start seconds")
        if start_seconds >= length:
            self.add_error("start_seconds", "Start seconds must be less than video length")
        if end_seconds > length:
            self.add_error("end_seconds", "End seconds cannot be greater than video length")

class TextQuoteForm(QuoteForm):
    class Meta:
        model = TextQuote
        fields = ["quote_text", "author", "text_title"]
        widgets = {
            'author': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Author'
                }),
            'text_title': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Title of Work'
                }),
            'quote_text': forms.Textarea(attrs={
                'class': "form-control",
                'placeholder': 'Quote Text'
                })
        }

    field_order = ["title", "description", "quote_text", "text_title", "author"]

essence/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Quote, TextQuote, YoutubeQuote, YoutubeVideo
from .forms import YoutubeQuoteForm, TextQuoteForm, RegisterForm
from .youtubeapi import video_id, video_info
from django.contrib.auth import authenticate, login


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            user = authenticate(request, username=form.cleaned_data["username"], password=form.cleaned_data["password1"])
            login(request, user)
            return redirect(reverse("essence:index"))
    else:
        form = RegisterForm()

    return render(request, "essence/register.html", {"form":form})


class IndexView(generic.TemplateView):
    template_name = "essence/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_anonymous:
            context["youtube_quotes"] = YoutubeQuote.objects.filter(user=self.request.user)
            context["text_quotes"] = TextQuote.objects.filter(user=self.request.user)
        return context
    
    
class TextQuoteIndexView(generic.ListView):
    template_name = "essence/list.html"
    context_object_name = "quotes"

    def get_queryset(self) -> QuerySet[Any]:
        return TextQuote.objects.filter(user=self.request.user).order_by("-metadata__entry_timestamp")
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["text"] = True
        return context
    

class YoutubeQuoteIndexView(generic.ListView):
    template_name = "essence/list.html"
    context_object_name = "quotes"

    def get_queryset(self) -> QuerySet[Any]:
        return YoutubeQuote.objects.filter(user=self.request.user).order_by("-metadata__entry_timestamp")
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["youtube"] = True
        return context
    
    
class YoutubeQuoteCreateView(generic.CreateView):
    template_name = "essence/create.html"
    model = YoutubeQuote
    form_class = YoutubeQuoteForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        ytquote = form.save(commit=False)
        youtube_id = video_id(form.cleaned_data['youtube_link'])
        query = YoutubeVideo.objects.filter(pk=youtube_id)
        # if we don't have the yt video yet, store it
        if len(query) == 0:
            info = video_info(youtube_id)
            youtube_video = YoutubeVideo(id = youtube_id, channel=info['channel'], title=info['title'], length=info['length'])
            youtube_video.save()
        else:
            youtube_video = query.get()
        ytquote.youtube_id = youtube_video
        quote = Quote(title=form.cleaned_data['title'], description=form.cleaned_data['description'])
        quote.save()
        ytquote.metadata = quote
        ytquote.user = self.request.user
        ytquote.save()
        
        self.success_url = reverse("essence:youtube_detail", args=(ytquote.pk,))
        return super().form_valid(form)
    

class YoutubeQuoteView(generic.DetailView):
    model = YoutubeQuote
    template_name = "essence/youtubedetail.html"
    

class TextQuoteCreateView(generic.CreateView):
    template_name = "essence/create.html"
    model = TextQuote
    form_class = TextQuoteForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        text_quote = form.save(commit=False)
        quote = Quote(title=form.cleaned_data['title'], description=form.cleaned_data['description'])
        quote.save()
        text_quote.metadata = quote
        text_quote.user = self.request.user
        text_quote.save()
        
        self.success_url = reverse("essence:text_detail", args=(text_quote.pk,))
        return super().form_valid(form)
    

class TextQuoteView(generic.DetailView):
    model = TextQuote
    template_name = "essence/textdetail.html"

essence/templates/essence/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load bootstrap5 %}
        {% load static %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <title>Essence</title>
        <link rel="icon" href="{% static 'essence/images/Essence.png' %}">
        <link rel="stylesheet" href="{% static 'essence/style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark static-top bg-dark">
            <div class="container-xl">
                <a class="navbar-brand" href="{% url 'essence:index' %}">
                    <img src="{% static 'essence/images/Essence.png' %}" alt="Essence Logo" width="40" height="40"/>
                    Essence
                </a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.view_name == 'essence:index' %}active{% endif %}" href="{% url 'essence:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.view_name == 'essence:text_index' or request.resolver_match.view_name == 'essence:text_detail' %}active{% endif %}" href="{% url 'essence:text_index' %}">
                                Text Quotes
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.resolver_match.view_name == 'essence:youtube_index' or request.resolver_match.view_name == 'essence:youtube_detail' %}active{% endif %}" href="{% url 'essence:youtube_index' %}">
                                Audio/Video Quotes
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a style="background-color: #212529; border-color: #212529;" class="btn btn-dark dropdown-toggle nav-link {% if request.resolver_match.view_name == 'essence:text_create' or request.resolver_match.view_name == 'essence:youtube_create' %}active{% endif %}" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-current="page">
                                New
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li>
                                    <a class="dropdown-item" href="{% url 'essence:text_create' %}">Text</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'essence:youtube_create' %}">Audio/Video</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            {%if user.is_authenticated %}
            <a class="btn btn-dark text-decoration-none mx-4" href="{% url 'logout' %}"> Logout</a>
            {%else%}
            <a class="btn btn-dark text-decoration-none mx-4" href="{% url 'login' %}"> Login</a>
            {%endif%}
        </nav>            
        <div id="content" class="pt-4 pb-4">
            {% block content %}
            {%endblock%}
        </div>
    </body>
</html>

essence/templates/essence/create.html
{%extends './base.html' %}
{%block content%}
<div class="col-4 mx-auto">
    <h1 class="display-6">Enter new quote...</h1>
    <form method="post">
        {%csrf_token %}
        <div class="form-group">
            {%for field in form%}
            {{field}}
            {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
                <br/>
            {% endfor %}
            <br/>
            {%endfor%}
            <input type="submit" value="Save" class="btn btn-success mx-auto"/>
        </div>
    </form>
</div>
{%endblock%}

essence/templates/essence/detail.html
{% extends './base.html' %}
{% block content %}
<div class="col-6 mx-auto">
    <div class="card" style="border-radius: 15px; background-color: #EEE;">
        <div class="card-body p-5">
            {%block quote_content%}
            {%endblock%}
        </div>
    </div>
    <div class="text-center pt-4">
        <h1 class="display-6">{{object.metadata.title}}</h1>
        {%if object.metadata.description %}
        <hr>
        <p>
            {{object.metadata.description}}
        </p>
        {%endif%}
        <p>
            <small class="text-muted"> Created {{object.metadata.entry_timestamp}}</small>
        </p>
    </div>
</div>
{% endblock %}

essence/templates/essence/index.html
{%extends './base.html' %}
{%block content%}
<div class="col-6 mx-auto">
    {%if user.is_authenticated %}
    <div class="text-center">
        <h1 class="display-1 font-weight-bold">Essence</h1>
        <p class="lead col-8 mx-auto">
            Ever read a passage in a book that felt especially poignant, or have a part of a song that really stands out?
            Essence is a website built to save and remember the essence of media like those.
            Currently, you can save a moment as a text quote or a video/audio quote via youtube with a start and end time.   
        </p>
        <br>
        <h1 class="display-6 font-weight-bold">
            Get started by creating a new text or Youtube quote:
        </h1>
    </div>
    <br>
    <div class="row col-6 mx-auto">
        <a class="col" href="{% url 'essence:text_create' %}">
            <button type="button" class="btn btn-outline-secondary btn-lg px-4 gap-3">Text Quote</button>
        </a>
        <a class="col" href="{% url 'essence:youtube_create' %}">
            <button type="button" class="btn btn-outline-danger btn-lg px-4 gap-3">Youtube Quote</button>
        </a>
    </div>
    <br>
    <h1 class="text-center">Your quotes at a glance...</h1>
    <h2>Text Quotes</h2>
    <ul>
        {% for quote in text_quotes %}
        <li>{{ quote.metadata.title }}</li>
        {% empty %}
        <li>No text quotes yet.</li>
        {% endfor %}
    </ul>
    <h2>Youtube Quotes</h2>
    <ul>
        {% for quote in youtube_quotes %}
        <li>{{ quote.metadata.title }}</li>
        {% empty %}
        <li>No youtube quotes yet.</li>
        {% endfor %}
    </ul>
    {%else%}
    <div class="text-center">
        <h1 class="display-1">Not Logged in?</h1>
        <br/>
        <a class="btn btn-primary" href="{% url 'login' %}">Log In</a>
        <br/>
        <h3 class="mt-4">New User?</h3>
        <a class="btn btn-secondary" href="{% url 'essence:register' %}">Create Account</a>
    </div>
    {%endif%}
</div>
{%endblock%}

essence/templates/essence/list.html
{% extends './base.html' %}
{% block content %}
    <h1 class="text-center display-2">Your Quotes...</h1><br/>
    <hr class="col-6 mx-auto" style="margin: 0;">
    {% for quote in quotes %}
    <div class="row col-6 mx-auto quoterow">
        {%if youtube %}
        <a href="{% url 'essence:youtube_detail' quote.pk %}" class="sneakylink"></a>
        {%endif%}
        {%if text %}
        <a href="{% url 'essence:text_detail' quote.pk %}" class="sneakylink"></a>
        {%endif%}
        <div class="row align-items-center">
            <p class="col lead display-6">
                {{quote.metadata.title}},
                <small class="fs-5">
                    {%if text %}
                    {{ quote.text_title }}
                    {% endif %}
                    {%if youtube %}
                    {{ quote.youtube_id.title }}
                    {% endif %}
                </small>
            </p>
            {%if youtube %} <img class="rounded col col-3 py-2" src="https://i.ytimg.com/vi/{{quote.youtube_id.id}}/sddefault.jpg"/> {%endif%}
        </div>
        <hr style="margin: 0;">
    </div>
    {%endfor%}
    {% endblock %}

essence/templates/essence/register.html
{% extends "./base.html" %}
{% load bootstrap5 %}
{% block content %}
<div class="col-4 mx-auto">
    <h2 class="text-center display-4">Create New User</h2>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
</div>
{% endblock %}

essence/templates/essence/textdetail.html
{%extends './detail.html'%}
{%block quote_content%}
<figure class="text-center mb-4">
    <blockquote class="blockquote">
        <p class="pb-3">
            <i class="fas fa-quote-left fa-xs text-primary"></i>
        <span class="lead">{{textquote.quote_text|linebreaks}}</span>
        <i class="fas fa-quote-right fa-xs text-primary"></i>
        </p>
    </blockquote>
    <figcaption class="blockquote-footer mb-0">
        {{textquote.author}}, <i> {{textquote.text_title}} </i>
    </figcaption>
</figure>
{%endblock%}

essence/templates/essence/youtubedetail.html
{%extends './detail.html'%}
{%block quote_content%}
<div id="player" class=""></div>
<script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>
<script type="text/javascript">
var player;
function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
        height: '400',
        width: '100%',
        videoId: '{{youtubequote.youtube_id.id}}',
        events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
        }
    });
}
function onPlayerReady(event) {
    loopStart();
    player.playVideo();
}
function loopStart() {
    player.seekTo({{youtubequote.start_seconds}});
}
function onPlayerStateChange(event) {
    if (event.data == YT.PlayerState.PLAYING) {
        setTimeout(loopStart, ({{youtubequote.end_seconds}} - {{youtubequote.start_seconds}})*1000);
    }
}
</script>
{%endblock%}